### ISSUE TITLE
If search string is empty do not make a Alamofire call

### ISSUE THREAD

**Issue by amunds1** [replayr/ios-client#16]

**Comment by amunds1** [comment]
@fshauge an empty search string leads to very long loading times, before the app crashes

**Comment by markushauge** [comment]
Passing an empty string to the API currently leads to an infinite wait period cause by the internal API calls receiving a 404 status code. Expected result is an empty array.

**Comment by markushauge** [comment]
This issue is only caused by the API, and should therefore be closed and reopened on the API's repository.
