### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by markushauge** [replayr/ios-client#5]
Clicking  the "Search" button multiple time spawns multiple asynchronous Alamofire calls resulting in multiple segues.

**Comment by amunds1** [comment]
**Could be solved using these**

Disable a button
http://stackoverflow.com/questions/33069204/how-can-i-prevent-user-from-clicking-the-button-twice-parse-xcode-swift

Loading indicator
https://github.com/icanzilb/SwiftSpinner

**Comment by amunds1** [comment]
Fixed issue
