### ISSUE TITLE
Play movie bug

### ISSUE THREAD

**Issue by markushauge** [replayr/ios-client#6]
Clicking "Play" multiple time opens multiple video player. Changing the app's orientation while loading the second movie, results in the video player being stuck.

**Comment by amunds1** [comment]
**Could be solved using these**

Disable a button
http://stackoverflow.com/questions/33069204/how-can-i-prevent-user-from-clicking-the-button-twice-parse-xcode-swift

Loading indicator
https://github.com/icanzilb/SwiftSpinner

App orientation should not change, since it is locked to portrait mode

**Comment by markushauge** [comment]
The video player has it's own orientation, so the problem still occurs

**Comment by amunds1** [comment]
Fixed issue
